// layout.ts - the card rules, read as data.
//
// Everything here is a lookup into card_layout.json, which is generated by
// `python3 scripts/card_layout.py --json` (`make web-data`). There is deliberately no table in this
// file: scripts/card_layout.py exists precisely so the layout, the scan rules and the format specs are
// declared once, and a hand-ported copy here would reintroduce the drift it prevents - silently, since
// the firmware-parity tests in scripts/test_sk_card.py only guard the Python side.
//
// The functions below are the Python module's query helpers (bank_for_path, scan_name_ok, all_dirs,
// format_target) re-expressed against that data.

import type { Bank, LayoutData } from './types.ts';

export const SCHEMA = 1;

export interface Layout {
  readonly data: LayoutData;
  readonly scan: LayoutData['scan'];
  readonly banks: Bank[];
  readonly allDirs: string[];
  readonly granularTapes: string[];
  readonly defaultConfig: string;
  readonly configProperties: Record<string, [number, number]>;
  readonly readmes: Record<string, string>;
  readonly rootReadme: LayoutData['root_readme'];

  bank(engine: string): Bank | undefined;
  isSidecar(name: string): boolean;
  isSourceExt(ext: string): boolean;
  isSkippedDir(name: string): boolean;
  /** Banks that accept audio at all - i.e. the ones `convert` can target. */
  audioBanks(): Bank[];
  bankForPath(rel: string): Bank | null;
  scanNameOk(name: string): boolean;
}

/**
 * Wrap a parsed card_layout.json. Throws on a schema the app does not understand, rather than
 * half-working against a newer export.
 */
export function makeLayout(data: LayoutData): Layout {
  if (!data || data.schema !== SCHEMA) {
    throw new Error(`card_layout.json: unsupported schema ${data && data.schema} (expected ${SCHEMA})`);
  }
  const byEngine = new Map(data.banks.map((b) => [b.engine, b]));
  const sidecars = new Set(data.sidecar_names);
  const sourceExts = new Set(data.source_extensions);
  const skipDirs = new Set(data.skip_dirs);

  return {
    data,
    scan: data.scan,
    banks: data.banks,
    allDirs: data.all_dirs,
    granularTapes: data.granular_tapes,
    defaultConfig: data.default_config,
    configProperties: data.config_properties,
    readmes: data.readmes,
    rootReadme: data.root_readme,

    bank: (engine) => byEngine.get(engine),
    isSidecar: (name) => sidecars.has(name.toUpperCase()),
    isSourceExt: (ext) => sourceExts.has(ext.toLowerCase()),
    isSkippedDir: (name) => skipDirs.has(name),

    audioBanks: () => data.banks.filter((b) => b.target),

    /**
     * Which bank owns this card-relative path? Longest directory match wins, so `SK/B` resolves to
     * granular rather than the `SK` platform entry.
     */
    bankForPath(rel) {
      let best: Bank | null = null;
      let bestLen = -1;
      for (const bank of data.banks) {
        for (const d of bank.dirs) {
          if ((rel === d || rel.startsWith(`${d}/`)) && d.length > bestLen) {
            best = bank;
            bestLen = d.length;
          }
        }
      }
      return best;
    },

    /** Would StreamDeck::scan_bank index a file with this name? Mirrors card_layout.scan_name_ok. */
    scanNameOk(name) {
      if (!name || name.startsWith('.')) return false;
      if (name.length > data.scan.max_name) return false;
      if (!name.includes('.')) return false;
      return data.scan.extensions.includes(name.split('.').pop()!.toLowerCase());
    },
  };
}

/**
 * A readable label for a bank's folders, matching how docs/sd-card.md writes them.
 *
 * `SK/B .. SK/Y` reads as a range of two folders rather than a set of six, and it makes granular's
 * relationship to the `SK` platform row - at the other end of the table - impossible to see. Collapsing
 * to the shared parent says it in one glance: `SK/{B,G,P,R,T,Y}`, `radio/{0..15}`.
 *
 * Lives here rather than in a view because two of them render the folder set and neither should have
 * to import the other to do it.
 */
export function folderLabel(dirs: string[]): string {
  if (dirs.length === 1) return dirs[0];
  const first = dirs[0];
  const cut = first.lastIndexOf('/');
  const parent = cut < 0 ? '' : first.slice(0, cut);
  const leaves = dirs.map((d) => d.slice(d.lastIndexOf('/') + 1));
  // Bail out if they do not actually share one parent - better a clumsy label than a wrong one.
  if (!dirs.every((d) => d.slice(0, d.lastIndexOf('/')) === parent)) return dirs.join(', ');
  const nums = leaves.map(Number);
  const contiguous = nums.every(Number.isInteger)
    && nums.every((n, i) => i === 0 || n === nums[i - 1] + 1);
  const set = contiguous ? `${nums[0]}..${nums[nums.length - 1]}` : leaves.join(',');
  return parent ? `${parent}/{${set}}` : `{${set}}`;
}

export interface TargetVars {
  deck?: string;
  bank?: number;
  tape?: string;
}

/**
 * Expand a bank's `target` template. Mirrors card_layout.format_target - keep the two in step; the
 * placeholder set is kept tiny for exactly that reason.
 */
export function formatTarget(template: string, i: number, vars: TargetVars = {}): string {
  const { deck = 'a', bank = 0, tape = 'B' } = vars;
  return template
    .replaceAll('{i02}', String(i).padStart(2, '0'))
    .replaceAll('{i}', String(i))
    .replaceAll('{deck}', deck)
    .replaceAll('{bank}', String(bank))
    .replaceAll('{tape}', tape);
}
