// wav.ts - WAV inspection and writing, mirroring scripts/card_audio.py byte for byte.
//
// This is one of only two things the web front-end reimplements rather than reading out of
// card_layout.json (the other is the verify walk). It is code, not content, so it cannot be shipped as
// data - and it is exactly the piece that must not drift, because a header this writes lands on a card
// the firmware reads. The guard is `web/test/fixtures/`: files generated by card_audio.py and asserted
// byte-identical here, so a change on either side fails a test rather than a device.
//
// Like the Python, the parser deliberately mirrors the FIRMWARE's chunk walk (src/memory/raw_stream.h)
// rather than being a general-purpose WAV reader: `verify`'s whole value is predicting what the device
// will do with a file, so where the firmware is lenient (extensible-format GUID, chunks before `data`)
// this is lenient in the same way, and where it is strict (fmt must precede data, 64-chunk bound) so is
// this.

import type { Encoding } from './types.ts';

export const F32: Encoding = 'f32';
export const INT16: Encoding = 'int16';
export const U8: Encoding = 'u8';
export const INT24: Encoding = 'int24';
export const INT32: Encoding = 'int32';

export const WAVE_FORMAT_PCM = 1;
export const WAVE_FORMAT_FLOAT = 3;
export const WAVE_FORMAT_EXTENSIBLE = 0xfffe;

export const MAX_CHUNKS = 64; // wav_source.h - kWavMaxChunks, the firmware's chunk-walk bound

/** The firmware's header parse would fail on this file (so it reads as empty / is skipped). */
export class WavError extends Error {}

/**
 * The parser needed to read past the bytes it was given. Thrown only when parsing a PREFIX of a file;
 * the caller re-reads more and retries. Separate from WavError because it is not a verdict about the
 * file - it says nothing is wrong yet.
 */
export class WavNeedMore extends Error {
  readonly needed: number;

  constructor(needed: number) {
    super(`need at least ${needed} bytes of header`);
    this.needed = needed;
  }
}

const ENC_LABEL = new Map<string, string>([
  [`${WAVE_FORMAT_FLOAT}/32`, '32-bit float'],
  [`${WAVE_FORMAT_PCM}/16`, '16-bit PCM'],
  [`${WAVE_FORMAT_PCM}/8`, '8-bit PCM'],
  [`${WAVE_FORMAT_PCM}/24`, '24-bit PCM'],
  [`${WAVE_FORMAT_PCM}/32`, '32-bit INTEGER PCM'],
]);

/** What the firmware would conclude about a WAV file. Mirrors card_audio.WavInfo. */
export class WavInfo {
  constructor(
    readonly fmt: number,
    readonly channels: number,
    readonly rate: number,
    readonly bits: number,
    readonly dataOffset: number,
    readonly dataSize: number,
  ) {}

  /** The firmware's `pcm_format_of` (src/memory/pcm_convert.h): null = it cannot decode this. */
  get encoding(): Encoding | null {
    if (this.fmt === WAVE_FORMAT_FLOAT && this.bits === 32) return F32;
    if (this.fmt !== WAVE_FORMAT_PCM) return null;
    switch (this.bits) {
      case 8: return U8;
      case 16: return INT16;
      case 24: return INT24;
      case 32: return INT32;
      default: return null;
    }
  }

  get frames(): number {
    const bytesPerFrame = Math.max(1, Math.floor(this.bits / 8) * Math.max(1, this.channels));
    return Math.floor(this.dataSize / bytesPerFrame);
  }

  get seconds(): number {
    return this.rate ? this.frames / this.rate : 0;
  }

  describe(): string {
    const enc = ENC_LABEL.get(`${this.fmt}/${this.bits}`) ?? `format tag ${this.fmt}, ${this.bits}-bit`;
    const ch = this.channels === 1 ? 'mono' : this.channels === 2 ? 'stereo' : `${this.channels}ch`;
    return `${enc}, ${ch}, ${this.rate} Hz`;
  }
}

const ascii = (view: DataView, off: number): string => String.fromCharCode(
  view.getUint8(off), view.getUint8(off + 1), view.getUint8(off + 2), view.getUint8(off + 3),
);

/**
 * Parse `bytes` the way the firmware does.
 *
 * @param bytes      the file, or a prefix of it long enough to cover the header
 * @param totalSize  the file's real length, when `bytes` is a prefix. The `data` chunk size is clamped
 *   against this exactly as the firmware clamps against the file length, so a truncated file reports
 *   the bytes that are actually there rather than what the header claims.
 */
export function parseWav(bytes: Uint8Array, totalSize: number = bytes.length): WavInfo {
  const size = totalSize;
  const have = bytes.length;
  if (size < 12) throw new WavError('file is too short to be a WAV (under 12 bytes)');
  if (have < 12) throw new WavNeedMore(12);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (ascii(view, 0) !== 'RIFF' || ascii(view, 8) !== 'WAVE') {
    throw new WavError("not a RIFF/WAVE file (missing the 'RIFF'/'WAVE' magic)");
  }

  let fmt = 0;
  let channels = 0;
  let bits = 0;
  let rate = 0;
  let haveFmt = false;
  let pos = 12;
  for (let n = 0; n < MAX_CHUNKS; n++) {
    if (pos + 8 > size) throw new WavError("ran off the end of the file without finding a 'data' chunk");
    if (pos + 8 > have) throw new WavNeedMore(pos + 8);
    const cid = ascii(view, pos);
    const csize = view.getUint32(pos + 4, true);
    const body = pos + 8;
    if (cid === 'fmt ') {
      if (csize < 16 || body + 16 > size) {
        throw new WavError("'fmt ' chunk is shorter than the 16 bytes the parser needs");
      }
      if (body + 16 > have) throw new WavNeedMore(body + 16);
      fmt = view.getUint16(body + 0, true);
      channels = view.getUint16(body + 2, true);
      rate = view.getUint32(body + 4, true);
      bits = view.getUint16(body + 14, true);
      if (fmt === WAVE_FORMAT_EXTENSIBLE && csize >= 40 && body + 26 <= size) {
        // WAVE_FORMAT_EXTENSIBLE: the real format tag is the first 2 bytes of the GUID. ffmpeg writes
        // this for some inputs; the firmware unwraps it (raw_stream.h:57-61).
        if (body + 26 > have) throw new WavNeedMore(body + 26);
        fmt = view.getUint16(body + 24, true);
      }
      haveFmt = true;
    } else if (cid === 'data') {
      if (!haveFmt) throw new WavError("'data' chunk appears before 'fmt ' - the parser needs fmt first");
      return new WavInfo(fmt, channels, rate, bits, body, Math.min(csize, size - body));
    }
    pos = body + csize + (csize & 1); // RIFF chunks are word-aligned
  }
  throw new WavError(`no 'data' chunk within the first ${MAX_CHUNKS} chunks`);
}

// --- writing -------------------------------------------------------------------------------------

/**
 * Anything indexable by sample: the decoder hands back Float32Array, the loop padder Float64Array,
 * and the tests write literal arrays because a four-sample expectation should look like four samples.
 */
export type Samples = Float32Array | Float64Array | number[];

/**
 * Encode samples to a body. Mirrors card_audio._pack.
 *
 * The int16 path matters for parity: Python does `int(s * 32767.0)` on a float64 after clipping, which
 * truncates toward zero. Math.trunc on a JS number (also float64) is the same operation - Math.round
 * would be off by one on roughly half of all samples.
 */
function pack(samples: Samples, encoding: Encoding): Uint8Array {
  const n = samples.length;
  if (encoding === F32) {
    const out = new Uint8Array(n * 4);
    const view = new DataView(out.buffer);
    for (let i = 0; i < n; i++) view.setFloat32(i * 4, samples[i], true);
    return out;
  }
  const out = new Uint8Array(n * 2);
  const view = new DataView(out.buffer);
  for (let i = 0; i < n; i++) {
    const s = Math.max(-1, Math.min(1, samples[i]));
    view.setInt16(i * 2, Math.trunc(s * 32767), true);
  }
  return out;
}

/**
 * Write a canonical 44-byte-header WAV. Interleaved samples for channels === 2.
 *
 * The plain 44-byte layout (no `fact`, no `LIST`) is deliberate even though the firmware now
 * chunk-walks: it is exactly what the device's own recorder writes (src/memory/wav.h - a fixed
 * BlocSize of 16 and a 44-byte static_assert), so a card built here is byte-shaped like a card the
 * device made, and stays readable by firmware predating the chunk-walk fix.
 */
export function writeWav(
  samples: Samples, rate: number, channels: number, encoding: Encoding,
): Uint8Array {
  const body = pack(samples, encoding);
  const bits = encoding === F32 ? 32 : 16;
  const fmt = encoding === F32 ? WAVE_FORMAT_FLOAT : WAVE_FORMAT_PCM;
  const blockAlign = (channels * bits) / 8;
  const out = new Uint8Array(44 + body.length);
  const view = new DataView(out.buffer);
  const tag = (off: number, s: string) => {
    for (let i = 0; i < 4; i++) view.setUint8(off + i, s.charCodeAt(i));
  };
  tag(0, 'RIFF');
  view.setUint32(4, 36 + body.length, true);
  tag(8, 'WAVE');
  tag(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, fmt, true);
  view.setUint16(22, channels, true);
  view.setUint32(24, rate, true);
  view.setUint32(28, rate * blockAlign, true); // byte rate
  view.setUint16(32, blockAlign, true);
  view.setUint16(34, bits, true);
  tag(36, 'data');
  view.setUint32(40, body.length, true);
  out.set(body, 44);
  return out;
}

/**
 * Write headerless signed-16-bit mono PCM - the radio engine's station format.
 *
 * There is no header, so nothing in the file records the sample rate: it is fixed by convention
 * (48 kHz) or overridden globally by radio/rate.txt. That is the whole reason this format is easy to
 * get wrong by hand and worth generating.
 */
export function writeRaw(samples: Samples): Uint8Array {
  return pack(samples, INT16);
}

/** Decode a WAV body to floats in [-1, 1]. Mirrors card_audio.read_samples. */
export function readSamples(bytes: Uint8Array): { samples: Float64Array; info: WavInfo } {
  const info = parseWav(bytes);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const start = info.dataOffset;
  if (info.encoding === F32) {
    const n = Math.floor(info.dataSize / 4);
    const out = new Float64Array(n);
    for (let i = 0; i < n; i++) out[i] = view.getFloat32(start + i * 4, true);
    return { samples: out, info };
  }
  if (info.encoding === INT16) {
    const n = Math.floor(info.dataSize / 2);
    const out = new Float64Array(n);
    for (let i = 0; i < n; i++) out[i] = view.getInt16(start + i * 2, true) / 32768;
    return { samples: out, info };
  }
  throw new WavError(`cannot decode ${info.describe()} - expected 32-bit float or 16-bit PCM`);
}

/**
 * Extend by looping until the encoded file clears a byte floor. Mirrors card_audio.pad_to_bytes.
 *
 * Needed because the scanned banks skip anything under 32 KB: a clip that is correct in every other
 * respect but 20 KB long is silently invisible - exactly the failure this tooling exists to prevent.
 */
export function padToBytes(samples: Samples, minBytes: number, bytesPerSample: number): Samples {
  if (!samples.length) return samples;
  const need = Math.ceil(minBytes / bytesPerSample);
  if (samples.length >= need) return samples;
  const out = new Float64Array(need);
  for (let i = 0; i < need; i++) out[i] = samples[i % samples.length];
  return out;
}
