// Cross-language parity on the OSC address space: does the host-side model compose the addresses the
// FIRMWARE actually resolves?
//
// `scripts/sk_osc.py` builds the layer-2 address space from the firmware tables so a generated control
// surface (`make tosc`) cannot advertise an address the device would reject. It is a second reading of
// those tables, though, and the shape rules on top of them - which kind segment a leaf takes, when a
// deck segment appears, the closed sets of stimulus and platform verbs - exist in `docs/dev/
// terminal-osc.md` and in `src/terminal/osc_addr.cpp`, not in any table either side can share. Nothing
// makes those two agree, and a disagreement is invisible: a layout bound to an address the resolver
// does not know produces a control that silently does nothing until someone tries it on a bench.
//
// So the model exports its whole address space (`host/osc_addresses.txt`, regenerated by
// `scripts/sk_osc.py --inventory`) and this test puts every line of it through the REAL
// `osc_dispatch_packet`. Two directions, because each catches a different mistake:
//
//   1. Every address the model composes must resolve. An address the resolver answers
//      `unknown-address` is a composition rule the model has wrong.
//   2. Every address `describe` advertises must be in the model. This is the direction that catches a
//      rule the model is MISSING - a new ParamId, a new query - which direction 1 cannot see, since a
//      smaller list still passes it.
//
// Direction 2 covers params, configs and state, which are the families the descriptor enumerates and
// the ones that move when the tables change. The stimulus and platform verbs are a closed set on both
// sides and are covered by direction 1 only.
//
// The engine here is a bare `IEngine`: everything not overridden is the base's default, which for the
// liveness masks is "all live". That is deliberate - it makes the whole space addressable, so this test
// is about the ADDRESS SPACE rather than about any engine's masking of it.
#include <cstdio>
#include <cstring>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "engine/iengine.h"
#include "osc_test_util.h"
#include "terminal/names.h"
#include "terminal/osc_addr.h"
#include "terminal/osc_sink.h"
#include "terminal/term_state.h"

using namespace spotykach;

namespace {

int g_failures = 0;
void check(bool cond, const std::string& msg) {
    if (!cond) { std::printf("  FAIL: %s\n", msg.c_str()); g_failures++; }
}

// Nothing is overridden but the three pure virtuals: the base's defaults leave every param and config
// live, which is what makes the whole address space reachable here.
struct AllLive : IEngine {
    void init(const EngineContext&) override {}
    void prepare() override {}
    void process(const float* const*, float**, size_t) override {}
};

// --- OSC packet construction --------------------------------------------------------------------------

void pad4(std::string& s) { while (s.size() & 3u) s.push_back('\0'); }

void put_be32(std::string& s, uint32_t v) {
    s.push_back(char(v >> 24)); s.push_back(char(v >> 16));
    s.push_back(char(v >> 8));  s.push_back(char(v));
}

// One message, built from an address and a type-tag string. `tags` empty means ",\0\0\0" - a message
// with no arguments, which is what a read and a bare trigger look like on the wire.
std::string message(const std::string& addr, const std::string& tags, const std::vector<float>& fs,
                    const std::vector<int32_t>& is) {
    std::string b = addr;
    b.push_back('\0');
    pad4(b);
    b += ",";
    b += tags;
    b.push_back('\0');
    pad4(b);
    size_t fi = 0, ii = 0;
    for (char t : tags) {
        if (t == 'f') {
            float v = fs[fi++];
            uint32_t bits;
            std::memcpy(&bits, &v, 4);
            put_be32(b, bits);
        } else if (t == 'i') {
            put_be32(b, static_cast<uint32_t>(is[ii++]));
        } else if (t == 's') {
            b += "a";
            b.push_back('\0');
            pad4(b);
        }
    }
    return b;
}

// The argument shape each kind of address takes, per the inventory's `argtype` column. This is the one
// piece of knowledge the test needs beyond the file itself, and getting it wrong shows up as `bad-arg`
// or `no-arg` rather than as a false pass: only `unknown-address` is read as a composition failure.
std::string probe_for(const std::string& addr, const std::string& kind, const std::string& argtype) {
    if (kind == "state" || kind == "dev") {
        if (argtype == "int") return message(addr, "i", {}, {0});     // preset slot
        if (argtype == "bool") return message(addr, "T", {}, {});     // mode/ack
        return message(addr, "", {}, {});                             // a read, or a bare verb
    }
    if (argtype == "float") return message(addr, "f", {0.5f}, {});
    if (argtype == "enum" || argtype == "int") return message(addr, "i", {}, {0});
    if (argtype == "bool") return message(addr, "T", {}, {});
    if (argtype == "int2") return message(addr, "ii", {}, {0, 60});
    if (argtype == "int3") return message(addr, "iii", {}, {0x90, 60, 100});
    return message(addr, "", {}, {});                                 // trigger
}

// Dispatch one packet and return every reply address+args, flattened.
std::vector<osctest::Reply> dispatch(const std::string& packet, IEngine& e) {
    osctest::StringOut out;
    OscSink   sink(out);
    TermState st;
    st.test_mode = true;   // stimulus verbs are refused in run mode; the address is what is under test
    osc_dispatch_packet(reinterpret_cast<const uint8_t*>(packet.data()), packet.size(), e, sink, st);
    return osctest::decode_replies(out.s);
}

bool rejected_as_unknown(const std::vector<osctest::Reply>& replies) {
    for (const auto& r : replies)
        if (r.addr == "/sk/err" && r.args.find("unknown-address") != std::string::npos) return true;
    return false;
}

// --- the inventory ------------------------------------------------------------------------------------

struct Entry {
    std::string address, kind, argtype;
};

std::vector<Entry> read_inventory(const char* path, bool& ok) {
    std::vector<Entry> out;
    std::ifstream f(path);
    ok = f.good();
    if (!ok) return out;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream s(line);
        Entry e;
        s >> e.address >> e.kind >> e.argtype;
        if (!e.address.empty()) out.push_back(e);
    }
    return out;
}

// Every address the describe bundle advertises, which is the device enumerating itself.
std::set<std::string> advertised(IEngine& e) {
    std::string pkt = message("/sk/dev/describe", "", {}, {});
    osctest::StringOut out;
    OscSink   sink(out);
    TermState st;
    osc_dispatch_packet(reinterpret_cast<const uint8_t*>(pkt.data()), pkt.size(), e, sink, st);

    std::set<std::string> addrs;
    for (const auto& r : osctest::decode_rows(out.s)) {
        if (r.addr.rfind("/sk/reply/dev/describe/", 0) != 0) continue;
        if (r.addr == "/sk/reply/dev/describe/caps") continue;
        // Each row's FIRST argument is the generic address it describes: `,s /sk/a/param/speed ...`.
        const size_t start = r.args.find("/sk/");
        if (start == std::string::npos) continue;
        size_t end = r.args.find(' ', start);
        addrs.insert(r.args.substr(start, end == std::string::npos ? end : end - start));
    }
    return addrs;
}

}  // namespace

int main(int argc, char** argv) {
    const char* path = argc > 1 ? argv[1] : "../host/osc_addresses.txt";
    std::printf("osc address parity (model <-> osc_addr.cpp)\n");

    bool ok = false;
    std::vector<Entry> inventory = read_inventory(path, ok);
    check(ok, std::string("could not read the inventory at ") + path +
              " - regenerate it with `scripts/sk_osc.py --inventory`");
    if (!ok) return 1;
    check(inventory.size() > 100, "the inventory is implausibly short");

    AllLive engine;

    // 1. Everything the model composes resolves.
    int unknown = 0;
    for (const Entry& e : inventory) {
        const auto replies = dispatch(probe_for(e.address, e.kind, e.argtype), engine);
        if (rejected_as_unknown(replies)) {
            std::printf("  FAIL: %s (%s %s) is unknown-address to the resolver\n",
                        e.address.c_str(), e.kind.c_str(), e.argtype.c_str());
            g_failures++;
            unknown++;
        }
    }
    std::printf("  %zu addresses probed, %d unresolved\n", inventory.size(), unknown);

    // 2. Everything describe advertises is in the model.
    //
    // This is the direction that first caught the descriptor advertising `/sk/state/cpu` for the four
    // platform reads the resolver answers at `/sk/dev/cpu`. Both spellings resolved, so direction 1
    // was green and nothing else in the tree compared the two - `describe_state_rows` now shares
    // `is_platform_read()` with the resolver, and this is the check that keeps them shared.
    std::set<std::string> have;
    for (const Entry& e : inventory) have.insert(e.address);
    const std::set<std::string> want = advertised(engine);
    check(!want.empty(), "describe advertised nothing - the bundle did not decode");
    int missing = 0;
    for (const std::string& a : want) {
        if (have.count(a)) continue;
        std::printf("  FAIL: describe advertises %s and the model does not compose it\n", a.c_str());
        g_failures++;
        missing++;
    }
    std::printf("  %zu addresses advertised by describe, %d missing from the model\n",
                want.size(), missing);

    // 3. A near miss must NOT resolve. Without this, a resolver that accepted anything would pass
    //    direction 1 outright, and these are the exact shapes the composition rules exist to reject.
    const char* bogus[] = {
        "/sk/a/size",              // no kind segment - `mix` is a param AND a query, so this is ambiguous
        "/sk/a/param/crossfade",   // a global param carrying a deck segment
        "/sk/param/speed",         // a deck-scoped param without one
        "/sk/a/param/tempo",       // platform-owned: set_param never sees it
        "/sk/a/param/modspeed",    // platform-owned too; it has its own stimulus address instead
        "/sk/c/param/size",        // a deck that does not exist
        "/sk/a/param/nosuch",      // a slot that does not exist
        "/sk/a/pad/nosuch",        // a stimulus verb that does not exist
        "/sk/dev/nosuch",
    };
    for (const char* a : bogus) {
        const auto replies = dispatch(message(a, "f", {0.5f}, {}), engine);
        const auto bare    = dispatch(message(a, "", {}, {}), engine);
        check(rejected_as_unknown(replies) || rejected_as_unknown(bare),
              std::string(a) + " should be unknown-address and is not");
    }

    if (g_failures) {
        std::printf("\nFAILED: %d check(s)\n", g_failures);
        return 1;
    }
    std::printf("PASSED\n");
    return 0;
}
