// layout.js - the card rules, read as data.
//
// Everything here is a lookup into card_layout.json, which is generated by
// `python3 scripts/card_layout.py --json` (`make web-data`). There is deliberately no table in this
// file: scripts/card_layout.py exists precisely so the layout, the scan rules and the format specs are
// declared once, and a hand-ported copy here would reintroduce the drift it prevents - silently, since
// the firmware-parity tests in scripts/test_sk_card.py only guard the Python side.
//
// The functions below are the Python module's query helpers (bank_for_path, scan_name_ok, all_dirs,
// format_target) re-expressed against that data.

/** @typedef {ReturnType<typeof makeLayout>} Layout */

/**
 * Wrap a parsed card_layout.json. Throws on a schema the app does not understand, rather than
 * half-working against a newer export.
 */
export function makeLayout(data) {
  if (!data || data.schema !== 1) {
    throw new Error(`card_layout.json: unsupported schema ${data && data.schema} (expected 1)`);
  }
  const byEngine = new Map(data.banks.map((b) => [b.engine, b]));
  const sidecars = new Set(data.sidecar_names);
  const sourceExts = new Set(data.source_extensions);
  const skipDirs = new Set(data.skip_dirs);

  return {
    data,
    scan: data.scan,
    banks: data.banks,
    allDirs: data.all_dirs,
    granularTapes: data.granular_tapes,
    defaultConfig: data.default_config,
    configProperties: data.config_properties,
    readmes: data.readmes,
    rootReadme: data.root_readme,

    bank: (engine) => byEngine.get(engine),
    isSidecar: (name) => sidecars.has(name.toUpperCase()),
    isSourceExt: (ext) => sourceExts.has(ext.toLowerCase()),
    isSkippedDir: (name) => skipDirs.has(name),

    /** Banks that accept audio at all - i.e. the ones `convert` can target. */
    audioBanks: () => data.banks.filter((b) => b.target),

    /**
     * Which bank owns this card-relative path? Longest directory match wins, so `SK/B` resolves to
     * granular rather than the `SK` platform entry.
     */
    bankForPath(rel) {
      let best = null;
      let bestLen = -1;
      for (const bank of data.banks) {
        for (const d of bank.dirs) {
          if ((rel === d || rel.startsWith(d + '/')) && d.length > bestLen) {
            best = bank;
            bestLen = d.length;
          }
        }
      }
      return best;
    },

    /** Would StreamDeck::scan_bank index a file with this name? Mirrors card_layout.scan_name_ok. */
    scanNameOk(name) {
      if (!name || name.startsWith('.')) return false;
      if (name.length > data.scan.max_name) return false;
      if (!name.includes('.')) return false;
      return data.scan.extensions.includes(name.split('.').pop().toLowerCase());
    },
  };
}

/**
 * Expand a bank's `target` template. Mirrors card_layout.format_target - keep the two in step; the
 * placeholder set is kept tiny for exactly that reason.
 */
export function formatTarget(template, i, { deck = 'a', bank = 0, tape = 'B' } = {}) {
  return template
    .replaceAll('{i02}', String(i).padStart(2, '0'))
    .replaceAll('{i}', String(i))
    .replaceAll('{deck}', deck)
    .replaceAll('{bank}', String(bank))
    .replaceAll('{tape}', tape);
}

/** Fetch and wrap card_layout.json. */
export async function loadLayout(url = './card_layout.json') {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`cannot load ${url}: HTTP ${res.status}`);
  return makeLayout(await res.json());
}
